### ISSUE TITLE
页面上边，左表效果，感觉保留一个就行

### ISSUE THREAD

**Issue by hunjixin** [jiaozifs/jiaozifs-ui#53]
![Image](https://github.com/jiaozifs/jiaozifs-ui/assets/41407352/78042b1c-b181-4562-95b9-613391ae5fe8)

现在感觉很不协调，感觉要不留一个左边的就行，上面的直接删掉

**Comment by TsumikiQAQ** [comment]
https://github.com/jiaozifs/jiaozifs-ui/pull/55
