### ISSUE TITLE
bug: 点击change里面的文件会跳转到主分支， 这应该是没有效果的

### ISSUE THREAD

**Issue by hunjixin** [jiaozifs/jiaozifs-ui#59]
![Image](https://github.com/jiaozifs/jiaozifs-ui/assets/41407352/4e70d6c7-b81e-4b96-8cf4-c4728ad17fd3)

**Comment by TsumikiQAQ** [comment]
https://github.com/jiaozifs/jiaozifs-ui/pull/68
