### ISSUE TITLE
feature： 上传拖转文件夹有多个文件的时候，上传的都是第一个文件

### ISSUE THREAD

**Issue by hunjixin** [jiaozifs/jiaozifs-ui#60]
只有第一个能成功，后面报错都是对象已经存在

![Image](https://github.com/jiaozifs/jiaozifs-ui/assets/41407352/d3d3fb78-a25d-4a32-825b-b66985a1fefd)

**Comment by TsumikiQAQ** [comment]
https://github.com/jiaozifs/jiaozifs-ui/pull/70
