### ISSUE TITLE
change列表中，在文件夹里面的文件没有显示全路径

### ISSUE THREAD

**Issue by hunjixin** [jiaozifs/jiaozifs-ui#63]
不显示全路径，两个文件夹里面相同名字的文件无法区分

![Image](https://github.com/jiaozifs/jiaozifs-ui/assets/41407352/41f8f0ba-baa4-4bea-8858-c8001064095f)

**Comment by TsumikiQAQ** [comment]
![image](https://github.com/jiaozifs/jiaozifs-ui/assets/116857998/594b8170-760c-4aa5-a707-1c062fbb02c3)
