### ISSUE TITLE
object页面在type=commit时，在点击文件夹，会变回显示branch上的内容

### ISSUE THREAD

**Issue by hunjixin** [jiaozifs/jiaozifs-ui#64]
1. 确保commit上有个文件夹
2.  在commit页面点击浏览对象，跳转到对象页面，此时显示正常
3. 在对象页面在点击文件夹会出现错误，显示的是main分支内容

这个跳转回来，再object页面上不用显示commit的change状态，会简单一些。

![Image](https://github.com/jiaozifs/jiaozifs-ui/assets/41407352/63428b66-c52d-4603-be4f-f32a15e96d53)

**Comment by TsumikiQAQ** [comment]
https://github.com/jiaozifs/jiaozifs-ui/pull/72
